//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись_в_ накладной.
    /// </summary>
    // *** Start programmer edit section *** (Запись_в_Накладной CustomAttributes)

    // *** End programmer edit section *** (Запись_в_Накладной CustomAttributes)
    [AutoAltered()]
    [Caption("Запись_в_ накладной")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Запись_в_НакладнойE", new string[] {
            "Количество as \'Количество\'",
            "Вес as \'Вес\'",
            "Цена as \'Цена\'",
            "Сумма as \'Сумма\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'"}, Hidden=new string[] {
            "Товар.Название"})]
    [MasterViewDefineAttribute("Запись_в_НакладнойE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class Запись_в_Накладной : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fВес;
        
        private double fЦена;
        
        private double fСумма;
        
        private IIS.АСУ_Склад.Товар fТовар;
        
        private IIS.АСУ_Склад.Накладная fНакладная;
        
        // *** Start programmer edit section *** (Запись_в_Накладной CustomMembers)

        // *** End programmer edit section *** (Запись_в_Накладной CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Запись_в_Накладной.Количество CustomAttributes)

        // *** End programmer edit section *** (Запись_в_Накладной.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Количество Get start)

                // *** End programmer edit section *** (Запись_в_Накладной.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Запись_в_Накладной.Количество Get end)

                // *** End programmer edit section *** (Запись_в_Накладной.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Количество Set start)

                // *** End programmer edit section *** (Запись_в_Накладной.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Запись_в_Накладной.Количество Set end)

                // *** End programmer edit section *** (Запись_в_Накладной.Количество Set end)
            }
        }
        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (Запись_в_Накладной.Вес CustomAttributes)

        // *** End programmer edit section *** (Запись_в_Накладной.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Вес Get start)

                // *** End programmer edit section *** (Запись_в_Накладной.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (Запись_в_Накладной.Вес Get end)

                // *** End programmer edit section *** (Запись_в_Накладной.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Вес Set start)

                // *** End programmer edit section *** (Запись_в_Накладной.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (Запись_в_Накладной.Вес Set end)

                // *** End programmer edit section *** (Запись_в_Накладной.Вес Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Запись_в_Накладной.Цена CustomAttributes)

        // *** End programmer edit section *** (Запись_в_Накладной.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Цена Get start)

                // *** End programmer edit section *** (Запись_в_Накладной.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Запись_в_Накладной.Цена Get end)

                // *** End programmer edit section *** (Запись_в_Накладной.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Цена Set start)

                // *** End programmer edit section *** (Запись_в_Накладной.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Запись_в_Накладной.Цена Set end)

                // *** End programmer edit section *** (Запись_в_Накладной.Цена Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Запись_в_Накладной.Сумма CustomAttributes)

        // *** End programmer edit section *** (Запись_в_Накладной.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Сумма Get start)

                // *** End programmer edit section *** (Запись_в_Накладной.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Запись_в_Накладной.Сумма Get end)

                // *** End programmer edit section *** (Запись_в_Накладной.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Сумма Set start)

                // *** End programmer edit section *** (Запись_в_Накладной.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Запись_в_Накладной.Сумма Set end)

                // *** End programmer edit section *** (Запись_в_Накладной.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Запись_в_ накладной.
        /// </summary>
        // *** Start programmer edit section *** (Запись_в_Накладной.Товар CustomAttributes)

        // *** End programmer edit section *** (Запись_в_Накладной.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.АСУ_Склад.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Товар Get start)

                // *** End programmer edit section *** (Запись_в_Накладной.Товар Get start)
                IIS.АСУ_Склад.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Запись_в_Накладной.Товар Get end)

                // *** End programmer edit section *** (Запись_в_Накладной.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Товар Set start)

                // *** End programmer edit section *** (Запись_в_Накладной.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Запись_в_Накладной.Товар Set end)

                // *** End programmer edit section *** (Запись_в_Накладной.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_Склад.Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Запись_в_Накладной.Накладная CustomAttributes)

        // *** End programmer edit section *** (Запись_в_Накладной.Накладная CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Накладная"})]
        public virtual IIS.АСУ_Склад.Накладная Накладная
        {
            get
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Накладная Get start)

                // *** End programmer edit section *** (Запись_в_Накладной.Накладная Get start)
                IIS.АСУ_Склад.Накладная result = this.fНакладная;
                // *** Start programmer edit section *** (Запись_в_Накладной.Накладная Get end)

                // *** End programmer edit section *** (Запись_в_Накладной.Накладная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись_в_Накладной.Накладная Set start)

                // *** End programmer edit section *** (Запись_в_Накладной.Накладная Set start)
                this.fНакладная = value;
                // *** Start programmer edit section *** (Запись_в_Накладной.Накладная Set end)

                // *** End programmer edit section *** (Запись_в_Накладной.Накладная Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Запись_в_НакладнойE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Запись_в_НакладнойE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Запись_в_НакладнойE", typeof(IIS.АСУ_Склад.Запись_в_Накладной));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Запись_в_Накладной.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗапись_в_Накладной CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗапись_в_Накладной CustomAttributes)
    public class DetailArrayOfЗапись_в_Накладной : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfЗапись_в_Накладной members)

        // *** End programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfЗапись_в_Накладной members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Запись_в_Накладной by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Запись_в_Накладной.
        /// </summary>
        public DetailArrayOfЗапись_в_Накладной(IIS.АСУ_Склад.Накладная fНакладная) : 
                base(typeof(Запись_в_Накладной), ((ICSSoft.STORMNET.DataObject)(fНакладная)))
        {
        }
        
        public IIS.АСУ_Склад.Запись_в_Накладной this[int index]
        {
            get
            {
                return ((IIS.АСУ_Склад.Запись_в_Накладной)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_Склад.Запись_в_Накладной dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
