//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [BusinessServer("IIS.АСУ_Склад.ПроверкаНаличияТоваров, АСУ_Склад.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "Статус as \'Статус\'",
            "Дата_Отгрузки as \'Дата_ отгрузки\'",
            "Дата_Оплаты as \'Дата_ оплаты\'",
            "Цена as \'Цена\'",
            "Номер as \'Номер\'",
            "Дата_Заполнения as \'Дата_ заполнения\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    [AssociatedDetailViewAttribute("ЗаказE", "Строка_Заказа", "Строка_ЗаказаE", true, "", "Строка_ заказа", true, new string[] {
            ""})]
    [View("ЗаказL", new string[] {
            "Статус as \'Статус\'",
            "Дата_Отгрузки as \'Дата_ отгрузки\'",
            "Дата_Оплаты as \'Дата_ оплаты\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    public class Заказ : IIS.АСУ_Склад.Документ
    {
        
        private IIS.АСУ_Склад.Состояние_Заказа fСтатус;
        
        private System.DateTime fДата_Отгрузки;
        
        private System.DateTime fДата_Оплаты;
        
        private IIS.АСУ_Склад.Сотрудник fСотрудник;
        
        private IIS.АСУ_Склад.DetailArrayOfСтрока_Заказа fСтрока_Заказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        public virtual IIS.АСУ_Склад.Состояние_Заказа Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                IIS.АСУ_Склад.Состояние_Заказа result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Дата_Отгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата_Отгрузки CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата_Отгрузки CustomAttributes)
        public virtual System.DateTime Дата_Отгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата_Отгрузки Get start)

                // *** End programmer edit section *** (Заказ.Дата_Отгрузки Get start)
                System.DateTime result = this.fДата_Отгрузки;
                // *** Start programmer edit section *** (Заказ.Дата_Отгрузки Get end)

                // *** End programmer edit section *** (Заказ.Дата_Отгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата_Отгрузки Set start)

                // *** End programmer edit section *** (Заказ.Дата_Отгрузки Set start)
                this.fДата_Отгрузки = value;
                // *** Start programmer edit section *** (Заказ.Дата_Отгрузки Set end)

                // *** End programmer edit section *** (Заказ.Дата_Отгрузки Set end)
            }
        }
        
        /// <summary>
        /// Дата_Оплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата_Оплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата_Оплаты CustomAttributes)
        public virtual System.DateTime Дата_Оплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата_Оплаты Get start)

                // *** End programmer edit section *** (Заказ.Дата_Оплаты Get start)
                System.DateTime result = this.fДата_Оплаты;
                // *** Start programmer edit section *** (Заказ.Дата_Оплаты Get end)

                // *** End programmer edit section *** (Заказ.Дата_Оплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата_Оплаты Set start)

                // *** End programmer edit section *** (Заказ.Дата_Оплаты Set start)
                this.fДата_Оплаты = value;
                // *** Start programmer edit section *** (Заказ.Дата_Оплаты Set end)

                // *** End programmer edit section *** (Заказ.Дата_Оплаты Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Цена CustomAttributes)

        // *** End programmer edit section *** (Заказ.Цена CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Цена Get)
                double цена = 0;
                for (int i = 0; i < this.Строка_Заказа.Count; i++)
                    цена += (double)this.Строка_Заказа[i].Сумма;
                return цена;
                // *** End programmer edit section *** (Заказ.Цена Get)
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Цена Set)

                // *** End programmer edit section *** (Заказ.Цена Set)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.АСУ_Склад.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Get start)

                // *** End programmer edit section *** (Заказ.Сотрудник Get start)
                IIS.АСУ_Склад.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказ.Сотрудник Get end)

                // *** End programmer edit section *** (Заказ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Set start)

                // *** End programmer edit section *** (Заказ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказ.Сотрудник Set end)

                // *** End programmer edit section *** (Заказ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Строка_Заказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.Строка_Заказа CustomAttributes)
        public virtual IIS.АСУ_Склад.DetailArrayOfСтрока_Заказа Строка_Заказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Строка_Заказа Get start)

                // *** End programmer edit section *** (Заказ.Строка_Заказа Get start)
                if ((this.fСтрока_Заказа == null))
                {
                    this.fСтрока_Заказа = new IIS.АСУ_Склад.DetailArrayOfСтрока_Заказа(this);
                }
                IIS.АСУ_Склад.DetailArrayOfСтрока_Заказа result = this.fСтрока_Заказа;
                // *** Start programmer edit section *** (Заказ.Строка_Заказа Get end)

                // *** End programmer edit section *** (Заказ.Строка_Заказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Строка_Заказа Set start)

                // *** End programmer edit section *** (Заказ.Строка_Заказа Set start)
                this.fСтрока_Заказа = value;
                // *** Start programmer edit section *** (Заказ.Строка_Заказа Set end)

                // *** End programmer edit section *** (Заказ.Строка_Заказа Set end)
            }
        }
        
        // *** Start programmer edit section *** (Заказ.Отменить CustomAttributes)

        // *** End programmer edit section *** (Заказ.Отменить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отменить()
        {
            // *** Start programmer edit section *** (Заказ.Отменить method implementation)
            return;
            // *** End programmer edit section *** (Заказ.Отменить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.АСУ_Склад.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.АСУ_Склад.Заказ));
                }
            }
        }
    }
}
