//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Накладная.
    /// </summary>
    // *** Start programmer edit section *** (Накладная CustomAttributes)

    // *** End programmer edit section *** (Накладная CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НакладнаяE", new string[] {
            "Статус as \'Статус\'",
            "Дата_Время_Отгрузки as \'Дата_ время_ отгрузки\'",
            "Сумма as \'Сумма\'",
            "Вес as \'Вес\'",
            "Примечание as \'Примечание\'",
            "ФИО_Получателя as \'Ф и о_ получателя\'",
            "Номер as \'Номер\'",
            "Дата_Заполнения as \'Дата_ заполнения\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    [AssociatedDetailViewAttribute("НакладнаяE", "Запись_в_Накладной", "Запись_в_НакладнойE", true, "", "Запись_в_ накладной", true, new string[] {
            ""})]
    [View("НакладнаяL", new string[] {
            "Статус as \'Статус\'",
            "Дата_Время_Отгрузки as \'Дата_ время_ отгрузки\'",
            "Сумма as \'Сумма\'",
            "Вес as \'Вес\'",
            "Примечание as \'Примечание\'",
            "ФИО_Получателя as \'Ф и о_ получателя\'",
            "Номер as \'Номер\'",
            "Дата_Заполнения as \'Дата_ заполнения\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    public class Накладная : IIS.АСУ_Склад.Документ
    {
        
        private IIS.АСУ_Склад.Состояние_Накладной fСтатус;
        
        private System.DateTime fДата_Время_Отгрузки;
        
        private double fСумма;
        
        private double fВес;
        
        private string fПримечание;
        
        private string fФИО_Получателя;
        
        private IIS.АСУ_Склад.Сотрудник fСотрудник;
        
        private IIS.АСУ_Склад.DetailArrayOfЗапись_в_Накладной fЗапись_в_Накладной;
        
        // *** Start programmer edit section *** (Накладная CustomMembers)

        // *** End programmer edit section *** (Накладная CustomMembers)

        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Статус CustomAttributes)

        // *** End programmer edit section *** (Накладная.Статус CustomAttributes)
        public virtual IIS.АСУ_Склад.Состояние_Накладной Статус
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Статус Get start)

                // *** End programmer edit section *** (Накладная.Статус Get start)
                IIS.АСУ_Склад.Состояние_Накладной result = this.fСтатус;
                // *** Start programmer edit section *** (Накладная.Статус Get end)

                // *** End programmer edit section *** (Накладная.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Статус Set start)

                // *** End programmer edit section *** (Накладная.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Накладная.Статус Set end)

                // *** End programmer edit section *** (Накладная.Статус Set end)
            }
        }
        
        /// <summary>
        /// Дата_Время_Отгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Дата_Время_Отгрузки CustomAttributes)

        // *** End programmer edit section *** (Накладная.Дата_Время_Отгрузки CustomAttributes)
        public virtual System.DateTime Дата_Время_Отгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Дата_Время_Отгрузки Get start)

                // *** End programmer edit section *** (Накладная.Дата_Время_Отгрузки Get start)
                System.DateTime result = this.fДата_Время_Отгрузки;
                // *** Start programmer edit section *** (Накладная.Дата_Время_Отгрузки Get end)

                // *** End programmer edit section *** (Накладная.Дата_Время_Отгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Дата_Время_Отгрузки Set start)

                // *** End programmer edit section *** (Накладная.Дата_Время_Отгрузки Set start)
                this.fДата_Время_Отгрузки = value;
                // *** Start programmer edit section *** (Накладная.Дата_Время_Отгрузки Set end)

                // *** End programmer edit section *** (Накладная.Дата_Время_Отгрузки Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Сумма CustomAttributes)

        // *** End programmer edit section *** (Накладная.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Сумма Get start)

                // *** End programmer edit section *** (Накладная.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Накладная.Сумма Get end)

                // *** End programmer edit section *** (Накладная.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Сумма Set start)

                // *** End programmer edit section *** (Накладная.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Накладная.Сумма Set end)

                // *** End programmer edit section *** (Накладная.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Вес CustomAttributes)

        // *** End programmer edit section *** (Накладная.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Вес Get start)

                // *** End programmer edit section *** (Накладная.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (Накладная.Вес Get end)

                // *** End programmer edit section *** (Накладная.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Вес Set start)

                // *** End programmer edit section *** (Накладная.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (Накладная.Вес Set end)

                // *** End programmer edit section *** (Накладная.Вес Set end)
            }
        }
        
        /// <summary>
        /// Примечание.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Примечание CustomAttributes)

        // *** End programmer edit section *** (Накладная.Примечание CustomAttributes)
        [StrLen(255)]
        public virtual string Примечание
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Примечание Get start)

                // *** End programmer edit section *** (Накладная.Примечание Get start)
                string result = this.fПримечание;
                // *** Start programmer edit section *** (Накладная.Примечание Get end)

                // *** End programmer edit section *** (Накладная.Примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Примечание Set start)

                // *** End programmer edit section *** (Накладная.Примечание Set start)
                this.fПримечание = value;
                // *** Start programmer edit section *** (Накладная.Примечание Set end)

                // *** End programmer edit section *** (Накладная.Примечание Set end)
            }
        }
        
        /// <summary>
        /// ФИО_Получателя.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ФИО_Получателя CustomAttributes)

        // *** End programmer edit section *** (Накладная.ФИО_Получателя CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО_Получателя
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ФИО_Получателя Get start)

                // *** End programmer edit section *** (Накладная.ФИО_Получателя Get start)
                string result = this.fФИО_Получателя;
                // *** Start programmer edit section *** (Накладная.ФИО_Получателя Get end)

                // *** End programmer edit section *** (Накладная.ФИО_Получателя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ФИО_Получателя Set start)

                // *** End programmer edit section *** (Накладная.ФИО_Получателя Set start)
                this.fФИО_Получателя = value;
                // *** Start programmer edit section *** (Накладная.ФИО_Получателя Set end)

                // *** End programmer edit section *** (Накладная.ФИО_Получателя Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Накладная.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.АСУ_Склад.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Сотрудник Get start)

                // *** End programmer edit section *** (Накладная.Сотрудник Get start)
                IIS.АСУ_Склад.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Накладная.Сотрудник Get end)

                // *** End programmer edit section *** (Накладная.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Сотрудник Set start)

                // *** End programmer edit section *** (Накладная.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Накладная.Сотрудник Set end)

                // *** End programmer edit section *** (Накладная.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Запись_в_Накладной CustomAttributes)

        // *** End programmer edit section *** (Накладная.Запись_в_Накладной CustomAttributes)
        public virtual IIS.АСУ_Склад.DetailArrayOfЗапись_в_Накладной Запись_в_Накладной
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Запись_в_Накладной Get start)

                // *** End programmer edit section *** (Накладная.Запись_в_Накладной Get start)
                if ((this.fЗапись_в_Накладной == null))
                {
                    this.fЗапись_в_Накладной = new IIS.АСУ_Склад.DetailArrayOfЗапись_в_Накладной(this);
                }
                IIS.АСУ_Склад.DetailArrayOfЗапись_в_Накладной result = this.fЗапись_в_Накладной;
                // *** Start programmer edit section *** (Накладная.Запись_в_Накладной Get end)

                // *** End programmer edit section *** (Накладная.Запись_в_Накладной Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Запись_в_Накладной Set start)

                // *** End programmer edit section *** (Накладная.Запись_в_Накладной Set start)
                this.fЗапись_в_Накладной = value;
                // *** Start programmer edit section *** (Накладная.Запись_в_Накладной Set end)

                // *** End programmer edit section *** (Накладная.Запись_в_Накладной Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НакладнаяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяE", typeof(IIS.АСУ_Склад.Накладная));
                }
            }
            
            /// <summary>
            /// "НакладнаяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяL", typeof(IIS.АСУ_Склад.Накладная));
                }
            }
        }
    }
}
