//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние_ заказа.
    /// </summary>
    // *** Start programmer edit section *** (Состояние_Заказа CustomAttributes)

    // *** End programmer edit section *** (Состояние_Заказа CustomAttributes)
    public enum Состояние_Заказа
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Заказа.Новый CustomAttributes)

        // *** End programmer edit section *** (Состояние_Заказа.Новый CustomAttributes)
        Новый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Заказа.Оплаченный CustomAttributes)

        // *** End programmer edit section *** (Состояние_Заказа.Оплаченный CustomAttributes)
        Оплаченный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Заказа.Отмененный CustomAttributes)

        // *** End programmer edit section *** (Состояние_Заказа.Отмененный CustomAttributes)
        Отмененный,
    }
}
