//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние_ накладной.
    /// </summary>
    // *** Start programmer edit section *** (Состояние_Накладной CustomAttributes)

    // *** End programmer edit section *** (Состояние_Накладной CustomAttributes)
    public enum Состояние_Накладной
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Накладной.Новая CustomAttributes)

        // *** End programmer edit section *** (Состояние_Накладной.Новая CustomAttributes)
        Новая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Накладной.Выписанная CustomAttributes)

        // *** End programmer edit section *** (Состояние_Накладной.Выписанная CustomAttributes)
        Выписанная,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Накладной.Приостановленная CustomAttributes)

        // *** End programmer edit section *** (Состояние_Накладной.Приостановленная CustomAttributes)
        Приостановленная,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Накладной.Готовая CustomAttributes)

        // *** End programmer edit section *** (Состояние_Накладной.Готовая CustomAttributes)
        Готовая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Состояние_Накладной.Отгруженная CustomAttributes)

        // *** End programmer edit section *** (Состояние_Накладной.Отгруженная CustomAttributes)
        Отгруженная,
    }
}
