//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка_ заказа.
    /// </summary>
    // *** Start programmer edit section *** (Строка_Заказа CustomAttributes)

    // *** End programmer edit section *** (Строка_Заказа CustomAttributes)
    [AutoAltered()]
    [Caption("Строка_ заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Строка_ЗаказаE", new string[] {
            "Количество as \'Количество\'",
            "Цена_с_Налогом as \'Цена_с_ налогом\'",
            "Сумма as \'Сумма\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'",
            "Товар.Цена",
            "Заказ"}, Hidden=new string[] {
            "Товар.Название",
            "Заказ"})]
    [MasterViewDefineAttribute("Строка_ЗаказаE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class Строка_Заказа : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.АСУ_Склад.Товар fТовар;
        
        private IIS.АСУ_Склад.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (Строка_Заказа CustomMembers)

        // *** End programmer edit section *** (Строка_Заказа CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Строка_Заказа.Количество CustomAttributes)

        // *** End programmer edit section *** (Строка_Заказа.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Строка_Заказа.Количество Get start)

                // *** End programmer edit section *** (Строка_Заказа.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Строка_Заказа.Количество Get end)

                // *** End programmer edit section *** (Строка_Заказа.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Строка_Заказа.Количество Set start)
                if (value < 0)
                {
                    Exception ex = new Exception("Значение количества не может быть отрицательным");
                    throw ex;
                }
                // *** End programmer edit section *** (Строка_Заказа.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Строка_Заказа.Количество Set end)

                // *** End programmer edit section *** (Строка_Заказа.Количество Set end)
            }
        }
        
        /// <summary>
        /// Цена_с_Налогом.
        /// </summary>
        // *** Start programmer edit section *** (Строка_Заказа.Цена_с_Налогом CustomAttributes)

        // *** End programmer edit section *** (Строка_Заказа.Цена_с_Налогом CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double Цена_с_Налогом
        {
            get
            {
                // *** Start programmer edit section *** (Строка_Заказа.Цена_с_Налогом Get)
                Double ценасналогами = 0;
                if (Товар != null && Товар.Цена > 0)
                {
                    ценасналогами = Товар.Цена * 1.35;
                }
                return ценасналогами;
                // *** End programmer edit section *** (Строка_Заказа.Цена_с_Налогом Get)
            }
            set
            {
                // *** Start programmer edit section *** (Строка_Заказа.Цена_с_Налогом Set)

                // *** End programmer edit section *** (Строка_Заказа.Цена_с_Налогом Set)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Строка_Заказа.Сумма CustomAttributes)

        // *** End programmer edit section *** (Строка_Заказа.Сумма CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Строка_Заказа.Сумма Get)
                Double сумма = 0;
                if (Товар != null && Товар.Цена > 0)
                {
                    сумма = Цена_с_Налогом * Количество;
                }
                return сумма;
                // *** End programmer edit section *** (Строка_Заказа.Сумма Get)
            }
            set
            {
                // *** Start programmer edit section *** (Строка_Заказа.Сумма Set)

                // *** End programmer edit section *** (Строка_Заказа.Сумма Set)
            }
        }
        
        /// <summary>
        /// Строка_ заказа.
        /// </summary>
        // *** Start programmer edit section *** (Строка_Заказа.Товар CustomAttributes)

        // *** End programmer edit section *** (Строка_Заказа.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.АСУ_Склад.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Строка_Заказа.Товар Get start)

                // *** End programmer edit section *** (Строка_Заказа.Товар Get start)
                IIS.АСУ_Склад.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Строка_Заказа.Товар Get end)

                // *** End programmer edit section *** (Строка_Заказа.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Строка_Заказа.Товар Set start)

                // *** End programmer edit section *** (Строка_Заказа.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Строка_Заказа.Товар Set end)

                // *** End programmer edit section *** (Строка_Заказа.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_Склад.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Строка_Заказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (Строка_Заказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.АСУ_Склад.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Строка_Заказа.Заказ Get start)

                // *** End programmer edit section *** (Строка_Заказа.Заказ Get start)
                IIS.АСУ_Склад.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Строка_Заказа.Заказ Get end)

                // *** End programmer edit section *** (Строка_Заказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Строка_Заказа.Заказ Set start)

                // *** End programmer edit section *** (Строка_Заказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Строка_Заказа.Заказ Set end)

                // *** End programmer edit section *** (Строка_Заказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Строка_ЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Строка_ЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Строка_ЗаказаE", typeof(IIS.АСУ_Склад.Строка_Заказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Строка_Заказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрока_Заказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрока_Заказа CustomAttributes)
    public class DetailArrayOfСтрока_Заказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfСтрока_Заказа members)

        // *** End programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfСтрока_Заказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Строка_Заказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Строка_Заказа.
        /// </summary>
        public DetailArrayOfСтрока_Заказа(IIS.АСУ_Склад.Заказ fЗаказ) : 
                base(typeof(Строка_Заказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.АСУ_Склад.Строка_Заказа this[int index]
        {
            get
            {
                return ((IIS.АСУ_Склад.Строка_Заказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_Склад.Строка_Заказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
