//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Код_Товара as \'Код_ товара\'",
            "Название as \'Название\'",
            "Единица_Измерения as \'Единица_ измерения\'",
            "Описание as \'Описание\'",
            "Цена as \'Цена\'",
            "Товар_на_Складе as \'Товар_на_ складе\'",
            "Товар_на_Складе.Количество as \'Количество\'"})]
    [View("ТоварL", new string[] {
            "Код_Товара as \'Код_ товара\'",
            "Название as \'Название\'",
            "Единица_Измерения as \'Единица_ измерения\'",
            "Описание as \'Описание\'",
            "Цена as \'Цена\'",
            "Товар_на_Складе.Количество as \'Количество\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод_Товара;
        
        private string fНазвание;
        
        private string fЕдиница_Измерения;
        
        private string fОписание;
        
        private double fЦена;
        
        private IIS.АСУ_Склад.Товар_на_Складе fТовар_на_Складе;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// Код_Товара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Код_Товара CustomAttributes)

        // *** End programmer edit section *** (Товар.Код_Товара CustomAttributes)
        public virtual int Код_Товара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Код_Товара Get start)

                // *** End programmer edit section *** (Товар.Код_Товара Get start)
                int result = this.fКод_Товара;
                // *** Start programmer edit section *** (Товар.Код_Товара Get end)

                // *** End programmer edit section *** (Товар.Код_Товара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Код_Товара Set start)

                // *** End programmer edit section *** (Товар.Код_Товара Set start)
                this.fКод_Товара = value;
                // *** Start programmer edit section *** (Товар.Код_Товара Set end)

                // *** End programmer edit section *** (Товар.Код_Товара Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Название CustomAttributes)

        // *** End programmer edit section *** (Товар.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Название Get start)

                // *** End programmer edit section *** (Товар.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Товар.Название Get end)

                // *** End programmer edit section *** (Товар.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Название Set start)

                // *** End programmer edit section *** (Товар.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Товар.Название Set end)

                // *** End programmer edit section *** (Товар.Название Set end)
            }
        }
        
        /// <summary>
        /// Единица_Измерения.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Единица_Измерения CustomAttributes)

        // *** End programmer edit section *** (Товар.Единица_Измерения CustomAttributes)
        [StrLen(255)]
        public virtual string Единица_Измерения
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Единица_Измерения Get start)

                // *** End programmer edit section *** (Товар.Единица_Измерения Get start)
                string result = this.fЕдиница_Измерения;
                // *** Start programmer edit section *** (Товар.Единица_Измерения Get end)

                // *** End programmer edit section *** (Товар.Единица_Измерения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Единица_Измерения Set start)

                // *** End programmer edit section *** (Товар.Единица_Измерения Set start)
                this.fЕдиница_Измерения = value;
                // *** Start programmer edit section *** (Товар.Единица_Измерения Set end)

                // *** End programmer edit section *** (Товар.Единица_Измерения Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Описание CustomAttributes)

        // *** End programmer edit section *** (Товар.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Описание Get start)

                // *** End programmer edit section *** (Товар.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Товар.Описание Get end)

                // *** End programmer edit section *** (Товар.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Описание Set start)

                // *** End programmer edit section *** (Товар.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Товар.Описание Set end)

                // *** End programmer edit section *** (Товар.Описание Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        // *** End programmer edit section *** (Товар.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Цена Get start)

                // *** End programmer edit section *** (Товар.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Товар.Цена Get end)

                // *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Цена Set start)

                // *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товар.Цена Set end)

                // *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Товар_на_Складе CustomAttributes)

        // *** End programmer edit section *** (Товар.Товар_на_Складе CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар_на_Складе"})]
        [NotNull()]
        public virtual IIS.АСУ_Склад.Товар_на_Складе Товар_на_Складе
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Товар_на_Складе Get start)

                // *** End programmer edit section *** (Товар.Товар_на_Складе Get start)
                IIS.АСУ_Склад.Товар_на_Складе result = this.fТовар_на_Складе;
                // *** Start programmer edit section *** (Товар.Товар_на_Складе Get end)

                // *** End programmer edit section *** (Товар.Товар_на_Складе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Товар_на_Складе Set start)

                // *** End programmer edit section *** (Товар.Товар_на_Складе Set start)
                this.fТовар_на_Складе = value;
                // *** Start programmer edit section *** (Товар.Товар_на_Складе Set end)

                // *** End programmer edit section *** (Товар.Товар_на_Складе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.АСУ_Склад.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.АСУ_Склад.Товар));
                }
            }
        }
    }
}
