//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар_на_ складе.
    /// </summary>
    // *** Start programmer edit section *** (Товар_на_Складе CustomAttributes)

    // *** End programmer edit section *** (Товар_на_Складе CustomAttributes)
    [AutoAltered()]
    [Caption("Товар_на_ складе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Товар_на_СкладеE", new string[] {
            "Количество as \'Количество\'"})]
    public class Товар_на_Складе : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.АСУ_Склад.Склад fСклад;
        
        // *** Start programmer edit section *** (Товар_на_Складе CustomMembers)

        // *** End programmer edit section *** (Товар_на_Складе CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Товар_на_Складе.Количество CustomAttributes)

        // *** End programmer edit section *** (Товар_на_Складе.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Товар_на_Складе.Количество Get start)

                // *** End programmer edit section *** (Товар_на_Складе.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Товар_на_Складе.Количество Get end)

                // *** End programmer edit section *** (Товар_на_Складе.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар_на_Складе.Количество Set start)

                // *** End programmer edit section *** (Товар_на_Складе.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Товар_на_Складе.Количество Set end)

                // *** End programmer edit section *** (Товар_на_Складе.Количество Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_Склад.Склад.
        /// </summary>
        // *** Start programmer edit section *** (Товар_на_Складе.Склад CustomAttributes)

        // *** End programmer edit section *** (Товар_на_Складе.Склад CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Склад"})]
        public virtual IIS.АСУ_Склад.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Товар_на_Складе.Склад Get start)

                // *** End programmer edit section *** (Товар_на_Складе.Склад Get start)
                IIS.АСУ_Склад.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Товар_на_Складе.Склад Get end)

                // *** End programmer edit section *** (Товар_на_Складе.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар_на_Складе.Склад Set start)

                // *** End programmer edit section *** (Товар_на_Складе.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Товар_на_Складе.Склад Set end)

                // *** End programmer edit section *** (Товар_на_Складе.Склад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Товар_на_СкладеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Товар_на_СкладеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Товар_на_СкладеE", typeof(IIS.АСУ_Склад.Товар_на_Складе));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Товар_на_Складе.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТовар_на_Складе CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТовар_на_Складе CustomAttributes)
    public class DetailArrayOfТовар_на_Складе : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfТовар_на_Складе members)

        // *** End programmer edit section *** (IIS.АСУ_Склад.DetailArrayOfТовар_на_Складе members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Товар_на_Складе by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Товар_на_Складе.
        /// </summary>
        public DetailArrayOfТовар_на_Складе(IIS.АСУ_Склад.Склад fСклад) : 
                base(typeof(Товар_на_Складе), ((ICSSoft.STORMNET.DataObject)(fСклад)))
        {
        }
        
        public IIS.АСУ_Склад.Товар_на_Складе this[int index]
        {
            get
            {
                return ((IIS.АСУ_Склад.Товар_на_Складе)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_Склад.Товар_на_Складе dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
