<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="ZakazE.aspx.cs" Inherits="IIS.АСУ_Склад.ЗаказE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Заказ</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСтатусLabel" runat="server" Text="Статус" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlСтатус" CssClass="descTxt" runat="server">
	<asp:ListItem>Новый</asp:ListItem>
<asp:ListItem>Оплаченный</asp:ListItem>
<asp:ListItem>Отмененный</asp:ListItem>

</asp:DropDownList>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДата_ОтгрузкиLabel" runat="server" Text="Дата_ отгрузки" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДата_Отгрузки" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДата_ОтгрузкиDatePickerValidator" runat="server" ControlToValidate="ctrlДата_Отгрузки" 
                        ErrorMessage="Введена некорректная дата: Дата_ отгрузки." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДата_ОплатыLabel" runat="server" Text="Дата_ оплаты" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДата_Оплаты" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДата_ОплатыDatePickerValidator" runat="server" ControlToValidate="ctrlДата_Оплаты" 
                        ErrorMessage="Введена некорректная дата: Дата_ оплаты." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlЦенаLabel" runat="server" Text="Цена" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox runat="server" CssClass="descTxt" ID="ctrlЦена">
</ac:DecimalTextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlНомерLabel" runat="server" Text="Номер" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlНомер" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДата_ЗаполненияLabel" runat="server" Text="Дата_ заполнения" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДата_Заполнения" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДата_ЗаполненияDatePickerValidator" runat="server" ControlToValidate="ctrlДата_Заполнения" 
                        ErrorMessage="Введена некорректная дата: Дата_ заполнения." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСотрудникLabel" runat="server" Text="Сотрудник" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlСотрудник" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlСотрудникRequiredFieldValidator" runat="server" ControlToValidate="ctrlСотрудник"
                            ErrorMessage="Не указано: Сотрудник" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСотрудник_ФамилияLabel" runat="server" Text="Фамилия" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlСотрудник_Фамилия" runat="server" ReadOnly="true">
</asp:TextBox>


</div>
<asp:ScriptManager ID="ScriptManager1" runat="server" >
</asp:ScriptManager>

<div style="clear: left">
	<ac:AjaxGroupEdit CssClass="$PERCENTMW$descTxt" ID="ctrlСтрока_Заказа" runat="server" ReadOnly="false" />
</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
<asp:Content ContentPlaceHolderID="ContentPlaceHolder0"  runat="server" >
	<script type="text/javascript">
		
		$(document).ready(function() {
			var lfName = '';
			var ordKeys = [];
			$('[id$=ctrlТовар]', '#<%=ctrlСтрока_Заказа.ClientID%>').each(
				function() {
					ordKeys.push($(this).val());
			});
			
			var changeLf = function() {
				$.ajax({
					type: "POST",
					url: window.location.pathname + "/CreateLf",
					dataType: "json",
					contentType: "application/json; charset=utf-8",
					data: JSON.stringify({ ordKeys: ordKeys, lfKey: lfName }),
					async: false, cache: false,
					success: function(data) {
						lfName = data.d;
					}
				});
				return false;
			}

			var changeAll = function() {
				ordKeys = [];
				var data = $('#<%=ctrlСтрока_Заказа.ClientID%>').ajaxgroupedit('getDataRows');
				$('[id$=ctrlТовар]', data).each(
					function() {
						ordKeys.push($(this).val());
					});
				changeLf();
				$('[id$=ctrlТовар]', data).each(
					function() {
						$(this).icsMasterEditorAjaxLookup('updateOptions', { lookup: { LFName: lfName } });
					});
			};
			/**
				* Перебираем в АГЕ ctrlСтрокаЗаказа все лукапы ctrlТовар и проставляем им измененный limit function.
				*/
			if (ordKeys) {
				changeLf();
				$('[id$=ctrlТовар]', '#<%=ctrlСтрока_Заказа.ClientID%>').each(
					function() {
						$(this).icsMasterEditorAjaxLookup('updateOptions', { lookup: { LFName: lfName } });
					});
			}
			/**
				* Если в одном из лукапов ctrlТовар поменяли значение - то переопределяем все лукапы ctrlТовар в АГЕ ctrlСтрокаЗаказа.
				*/
			$( '#<%=ctrlСтрока_Заказа.ClientID%>' ).on('change', '[id$=ctrlТовар]', function() {
				changeAll();
				autoCalc(this, this.parentNode.parentNode.parentNode.parentNode);
			});
			/**
				* Если добавлена новая строка в АГЕ, сразу назначим limit function.
				* @param {int} row Номер добавленной строки.
				*/
			$('#<%=ctrlСтрока_Заказа.ClientID%>').on('rowadded.ajaxgroupedit', function(e, d) {
				$('[id$=ctrlТовар]', d).icsMasterEditorAjaxLookup('updateOptions', { lookup: { LFName: lfName } });
			});
			/**
				* Если удалена строка в АГЕ, сразу изменяем limit function.
				*/
			$('#<%=ctrlСтрока_Заказа.ClientID%>').on('rowdeleted.ajaxgroupedit', function () {
				changeAll();
			});

			var autoCalc = function (_this, row) {
				var col = parseInt($('[id$=ctrlКоличество]', row).val());
				var price = parseFloat($('[id$=ctrlТовар_Цена]', row).text());
				price = price ? price : 0; 
				var pricetax = 1.35 * price;
				$('[id$=ctrlЦенаСНалогами]', row).text(pricetax.toFixed(2));
				$('[id$=ctrlСумма]', row).text((col * pricetax).toFixed(2));
				var sum = 0;
				$('[id$=ctrlСумма]', '#<%=ctrlСтрока_Заказа.ClientID%>').each(
					function() {
						sum += parseFloat($(this).text());
					});

				$('#<%=ctrlЦена.ClientID%>').val(sum.toFixed(2));
			}

			/**
				* Вычисление цены и суммы.
				*/
			$('#<%=ctrlСтрока_Заказа.ClientID%>').on('change', '[id$=ctrlКоличество]', function (e) {
				autoCalc(this, this.parentNode.parentNode.parentNode);
			});
		});

	</script>
</asp:Content>


